jobs:
  CI:
    secrets: inherit
    strategy:
      matrix:
        include:
        - jdk: 8
          os: ubuntu-latest
        - jdk: 17
          os: ubuntu-latest
        - jdk: 8
          os: windows-latest
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' ||
      github.event_name == 'schedule') }}
    needs:
    - CI
    - IT
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
  IT:
    secrets: inherit
    uses: ./.github/workflows/it.yml
    with:
      branch: 4.x
      jdk: 8
name: vertx-web (4.x)
on:
  repository_dispatch:
    types: trigger-ga___ci-4.x.yml
