jobs:
  CI:
    secrets: inherit
    strategy:
      matrix:
        include:
        - jdk: 11
          os: ubuntu-latest
        - jdk: 17
          os: ubuntu-latest
        - jdk: 11
          os: windows-latest
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' ||
      github.event_name == 'schedule') }}
    needs:
    - CI
    - IT
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: 11
  IT:
    secrets: inherit
    uses: ./.github/workflows/it.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: 11
name: vertx-web (5.x)
on:
  repository_dispatch:
    types: trigger-ga___ci-5.x.yml
