jobs:
  Test:
    name: Run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ inputs.jdk }}
    - continue-on-error: true
      name: Run tests
      run: mvn -s .github/maven-ci-settings.xml clean verify -B
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
