jobs:
  GraphQLWS-Tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ inputs.jdk }}
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      run: sh vertx-web-graphql/start-graphql-ws-tests-server.sh
    - continue-on-error: true
      run: npm install
      working-directory: vertx-web-graphql/tests/graphql-ws
    - continue-on-error: true
      run: npm run test
      working-directory: vertx-web-graphql/tests/graphql-ws
    - continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: GraphQLWSTestsServer.log
        path: ~/GraphQLWSTestsServer.log
    - continue-on-error: true
      if: ${{ always() }}
      run: sh stop-graphql-ws-tests-server.sh
      working-directory: vertx-web-graphql
    strategy:
      fail-fast: false
      matrix:
        node-version:
        - 18.13.0
  SockJS-WriteHandler-Tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ inputs.jdk }}
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      run: sh vertx-web/start-sockjs-write-handler-tests-server.sh
    - continue-on-error: true
      run: npm install
      working-directory: vertx-web/tests/sockjs
    - continue-on-error: true
      run: npm run test
      working-directory: vertx-web/tests/sockjs
    - continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: SockJSWriteHandlerTestServer.log
        path: ~/SockJSWriteHandlerTestServer.log
    - continue-on-error: true
      if: ${{ always() }}
      run: sh stop-sockjs-write-handler-tests-server.sh
      working-directory: vertx-web
    strategy:
      fail-fast: false
      matrix:
        node-version:
        - 16.13.1
name: IT
on:
  repository_dispatch:
    types: trigger-ga___it.yml
